### PR TITLE
Adding gnuplot script for calibration plots

### PR DESCRIPTION
**Pull request by msushkov**

### CODE REVIEW

**Comment by dennybritz** [comment]
Have you tested it? This is what I am getting:

```
17:56:30.249 [default-dispatcher-5][$a][CalibrationDataWriter] INFO  Running 'gnuplot -e "input_file='/Users/dennybritz/research/deepdive/target/calibration/titles.has_extractions.tsv';output_file='/Users/dennybritz/research/deepdive/target/calibration/titles.has_extractions.png'" /Users/dennybritz/research/deepdive/util/calibration.plg' to generate the calibration plot.

"input_file='/Users/dennybritz/research/deepdive/target/calibration/titles.has_extractions.tsv';output_file='/Users/dennybritz/research/deepdive/target/calibration/titles.has_extractions.png'"
^
line 0: invalid command
```

**Comment by dennybritz** [comment]
My guess: You can't start processes with spaced in quoted strings, you need to use a Seq(), see this for an example: http://www.scala-lang.org/api/current/index.html#scala.sys.process.package

**Comment by msushkov** [comment]
Yeah i left a comment in the scala file... I think it is because of gmuplot
warns

**Comment by dennybritz** [comment]
No, the command doesn't work. I'll fix it, may be faster since you haven't worked with Scala before.

**Comment by dennybritz** [comment]
(Unless you want to look into it?) Up to you.

**Comment by msushkov** [comment]
Sure, I can fix it. I have worked with Scala before :)

**Comment by dennybritz** [comment]
Ah ok, thanks. Pretty sure it's the Seq thing.

**Comment by msushkov** [comment]
do you mind taking a quick look at it? i tried to do what the documentation
page said but it still didnt work... the error is:

"input_file='/Users/msushkov/Dropbox/Stanford/deepdive/target/calibration/people.smokes.tsv';output_file='/Users/msushkov/Dropbox/Stanford/deepdive/target/calibration/people.smokes.png'"
^
line 0: invalid command

you will probably be much more efficient since i am not familiar with the
code... seems like it should be a quick fix but if not then let me know and
i can dig deeper into it.

**Comment by dennybritz** [comment]
Done, thanks! See 937c14a8759acb9860f735d509ffdea8b83666a3

**Comment by msushkov** [comment]
Wow, I was doing the exact same thing except I had outer quotes on the s"""input_file='${file.getCanonicalPath}';output_file='${plotOutputFile}'""" (4 outer quotes instead of 3)...

**Pull request merged**
