### PR TITLE
Modified Greenplum Tutorial to add Centos

### PR DESCRIPTION
**Pull request by zifeishan**
Most of the process should be fine, but I run across some bugs though.. Will talk with Ce about it.

### CODE REVIEW

**Comment by dennybritz** [comment]
@zifeishan Thanks! We made some changes to the Greenplum guide since you last submitted the pull request, could you pull the changes and merge it with your new one? This one gives me conflicts.. Thanks!

**Comment by dennybritz** [comment]
@zifeishan Any update on this? :)

**Comment by zifeishan** [comment]
Should be good now. Merged with `dennybritz:deepdive` branch `gh-pages`.

Removed the guide for Mac.

**Comment by dennybritz** [comment]
That's great, thanks!

**Pull request merged**
